# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    app.asset_upload_directory: '%kernel.project_dir%/public/cdn_uploads'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\Asset\AssetStorageService:
        arguments:
            $uploadDirectory: '%app.asset_upload_directory%'
